language: php

php:
  - 5.6
  - 5.5
  - hhvm

env:
  - LARAVEL_VERSION="~5.1" TESTBENCH_VERSION="~3.1"

before_script:
  - composer self-update
  - composer install

script: phpunit

notifications:
  slack: asgardcms:85rIXCjkamzxitmc0opndGga

matrix:
  allow_failures:
    - php: hhvm
